# Generated by Django 5.1.7 on 2025-03-25 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offduty',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='sleepberth',
            name='current_location',
        ),
        migrations.AlterField(
            model_name='sleepberth',
            name='log_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeping_logs', to='trips.log'),
        ),
        migrations.CreateModel(
            name='OnDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('log_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onduty_logs', to='trips.log')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
